services:
  inference_api:
    build:
      context: .
      dockerfile: inference/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - monitor-net
    volumes:
      - ./configs:/app/configs

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./inference/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge 